### ISSUE TITLE
Data Exploration: Missing Values

### ISSUE THREAD

**Issue by PatrykGadziomski** [PatrykGadziomski/Introducion-to-Data-Science-Repo#2]

**Comment by TrisRuhm** [comment]
![Image](https://github.com/PatrykGadziomski/Introducion-to-Data-Science-Repo/assets/145976224/902d551d-fa97-45d1-be7d-7785c2e00a60)

**Comment by TrisRuhm** [comment]
![Image](https://github.com/PatrykGadziomski/Introducion-to-Data-Science-Repo/assets/145976224/5b6b4214-3d57-47de-875d-0f824710303f)

**Comment by TrisRuhm** [comment]
- There are  94  rows with missing values

- Totally, 96 values are missing
