### ISSUE TITLE
Data Exploration: descriptive statistics and create tables

### ISSUE THREAD

**Issue by PatrykGadziomski** [PatrykGadziomski/Introducion-to-Data-Science-Repo#6]

**Comment by prarichut71244** [comment]
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

data = '/content/BikeRentalDaily_train.csv'

df = pd.read_csv(data)

df.shape

df.head()

df.info()

df.isnull().sum()

df.describe()

df.describe(include=['object'])

df.describe(include='all')
